name: Deploy Application to Production
on:
  push:
    branches: [ master ]

jobs:
  ci-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install Dependencies Node [Sage Theme]
        working-directory: ./web/app/themes/sage
        run: npm install && npm run build

      - name: Install Dependencies Composer [Sage Theme]
        working-directory: ./web/app/themes/sage
        run: composer install --no-dev --optimize-autoloader

      - name: Install Dependencies [WordPress Bedrock]
        run: composer install --no-dev --optimize-autoloader

      - name: Upload Artefacts for Deployment
        uses: actions/upload-artifact@v4
        with:
          name: prod-deploy
          path: ./
          include-hidden-files: true

  cd-deploy:
    needs: ci-deploy
    runs-on: self-hosted

    steps:
      - name: Define Environment Variables
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          RELEASE_DIR="/home/ec2-user/releases/$TIMESTAMP"
          CURRENT_SYMLINK="/home/ec2-user/project"
          echo "RELEASE_DIR=$RELEASE_DIR" >> $GITHUB_ENV
          echo "CURRENT_SYMLINK=$CURRENT_SYMLINK" >> $GITHUB_ENV

      - name: Download Artefacts from CI
        uses: actions/download-artifact@v4
        with:
          name: prod-deploy

      - name: Define New Release Path
        id: release_path
        run: |
          mkdir -p $RELEASE_DIR

      - name: Move Artefacts to Release Directory
        run: |
          rsync -av --remove-source-files $(pwd)/ ${{ env.RELEASE_DIR }}/

      - name: Swap Symlink to New Release
        run: |
          ln -sfn ${{ env.RELEASE_DIR }} ${{ env.CURRENT_SYMLINK }}

      - name: Lando Rebuild
        working-directory: ${{ env.CURRENT_SYMLINK }}
        run: lando start -y

      - name: Clean Up Old Releases
        run: |
          ls -t /home/ec2-user/releases/ | tail -n +5 | xargs -I {} rm -rf /home/ec2-user/releases/{}

