name: Deploy Application to Production
on:
  push:
    branches: [ master ]

jobs:
  ci-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install Dependencies Node [Sage Theme]
        working-directory: ./web/app/themes/sage
        run: npm install && npm run build

      - name: Install Dependencies Composer [Sage Theme]
        working-directory: ./web/app/themes/sage
        run: composer install --no-dev --optimize-autoloader

      - name: Install Dependencies [WordPress Bedrock]
        run: composer install --no-dev --optimize-autoloader

      - name: Upload Artefacts for Deployment
        uses: actions/upload-artifact@v4
        with:
          name: prod-deploy
          path: ./
          include-hidden-files: true

  cd-deploy:
    needs: ci-deploy
    runs-on: self-hosted

    steps:
      - name: Define Environment Variables
        run: |
          PROJECT_PATH="/home/ec2-user/project"
          echo "PROJECT_PATH=$PROJECT_PATH" >> $GITHUB_ENV

      - name: Download Artefacts from CI
        uses: actions/download-artifact@v4
        with:
          name: prod-deploy

      - name: Move Artefacts to Release Directory
        run: |
          rsync -av --remove-source-files $(pwd)/ ${{ env.PROJECT_PATH }}/
