name: Deploy Application to Production
on:
  push:
    branches: [ master ]

jobs:
  ci-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Permissions and Ownership
        run: |
          sudo find . -type d -exec chmod 755 {} \;
          sudo find . -type f -exec chmod 644 {} \;

      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install Dependencies Node [Sage Theme]
        working-directory: ./web/app/themes/sage
        run: npm install && npm run build

      - name: Install Dependencies Composer [Sage Theme]
        working-directory: ./web/app/themes/sage
        run: composer install --no-dev --optimize-autoloader

      - name: Install Dependencies [WordPress Bedrock]
        run: composer install --no-dev --optimize-autoloader

  # cd-deploy:
  #   needs: ci-deploy
  #   runs-on: self-hosted
