name: Deploy Application to Production
on:
  push:
    branches: [ master ]

jobs:
  ci-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./
        pre-command: |
          sudo find . -type d -exec chmod 755 {} \;
          sudo find . -type f -exec chmod 644 {} \;
          sudo chmod -R 775 web/app/uploads || true
          sudo chown -R $USER:$USER .

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Set up Composer
        uses: php-actions/composer@v6
        with:
          php_version: '8.3'

      - name: Install Dependencies [Sage Theme]
        working-directory: ./web/app/themes/sage
        run: |
          composer install --no-dev --optimize-autoloader
          npm install
          npm run build

      - name: Install Plugins and Dependencies [WordPress]
        working-directory: ./
        run: composer install --no-dev --optimize-autoloader

  # cd-deploy:
  #   needs: ci-deploy
  #   runs-on: self-hosted
